/**
 * OrderDetailPage
 * Container page for viewing and managing a single order
 */

import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useParams, useNavigate } from 'react-router-dom';
import { Button, Card, Form, Image, Input, InputNumber, Modal, Select, Space, Spin, Table, Tabs, Tag, Typography } from 'antd';
import { DeleteOutlined, EyeOutlined, FileImageOutlined, FilePdfOutlined, PlusOutlined, ReloadOutlined } from '@ant-design/icons';
import { PaymentMethod, PaymentStatus, PaymentType } from '@bakery-cms/common';
import { OrderDetail } from '../../components/features/orders/OrderDetail/OrderDetail';
import { OrderForm } from '../../components/features/orders/OrderForm/OrderForm';
import { LoadingSpinner } from '../../components/shared/LoadingSpinner/LoadingSpinner';
import { EmptyState } from '../../components/shared/EmptyState/EmptyState';
import { useModal } from '../../hooks/useModal';
import { useNotification } from '../../hooks/useNotification';
import {
  getOrderById,
  updateOrder,
  deleteOrder,
  confirmOrder,
  updateOrderExtras,
  cancelOrder,
  getOrderBills,
  saveOrderBill,
  voidOrderBill,
} from '../../services/order.service';
import { getAllPayments, refundOrderPayment } from '../../services/payment.service';
import { settingsService } from '../../services/settings.service';
import type { Order, OrderBill, OrderBillSnapshot } from '../../types/models/order.model';
import type { Payment, VietQRData } from '../../types/models/payment.model';
import type {
  InvoiceLanguage,
  OrderExtraFeeTemplate,
  StoreProfile,
} from '../../types/models/settings.model';
import type { OrderFormValues } from '../../components/features/orders/OrderForm/OrderForm.types';
import type { ColumnsType } from 'antd/es/table';
import { formatCurrency, formatDateTime } from '../../utils/format.utils';

const { Text } = Typography;

type RefundFormValues = {
  amount: number;
  method: PaymentMethod;
  transactionId?: string;
  notes?: string;
};

type ExtraFeeFormValues = {
  id: string;
  name?: string;
  amount: number;
};

type ManageExtrasFormValues = {
  extraFees: ExtraFeeFormValues[];
  paymentMethod?: PaymentMethod;
  paymentNotes?: string;
};

type BillLanguagePack = {
  language: InvoiceLanguage;
  locale: string;
  invoiceTitle: string;
  customer: string;
  phone: string;
  address: string;
  walkInCustomer: string;
  na: string;
  productCode: string;
  productCodeShort: string;
  productName: string;
  items: string;
  qty: string;
  unitPrice: string;
  subtotal: string;
  orderSummary: string;
  itemsTotal: string;
  extraFees: string;
  extraFeesTotal: string;
  grandTotal: string;
  notes: string;
  noItems: string;
  generatedBy: string;
  itemNotePrefix: string;
};

const BILL_LANGUAGE_PACKS: Record<InvoiceLanguage, BillLanguagePack> = {
  vi: {
    language: 'vi',
    locale: 'vi-VN',
    invoiceTitle: 'HÓA ĐƠN BÁN HÀNG',
    customer: 'Khách hàng',
    phone: 'Số điện thoại',
    address: 'Địa chỉ nhận',
    walkInCustomer: 'Khách lẻ',
    na: 'N/A',
    productCode: 'Mã sản phẩm',
    productCodeShort: 'Mã',
    productName: 'Tên sản phẩm',
    items: 'Sản phẩm',
    qty: 'SL',
    unitPrice: 'Đơn giá',
    subtotal: 'Thành tiền',
    orderSummary: 'Tổng kết đơn',
    itemsTotal: 'Tiền hàng',
    extraFees: 'Phí bổ sung',
    extraFeesTotal: 'Tổng phí bổ sung',
    grandTotal: 'Tổng cộng',
    notes: 'Ghi chú',
    noItems: 'Không có sản phẩm',
    generatedBy: 'Tạo bởi Bakery CMS',
    itemNotePrefix: 'Ghi chú',
  },
  en: {
    language: 'en',
    locale: 'en-US',
    invoiceTitle: 'SALES BILL',
    customer: 'Customer',
    phone: 'Phone',
    address: 'Address',
    walkInCustomer: 'Walk-in Customer',
    na: 'N/A',
    productCode: 'Product Code',
    productCodeShort: 'Code',
    productName: 'Product Name',
    items: 'Items',
    qty: 'Qty',
    unitPrice: 'Unit Price',
    subtotal: 'Subtotal',
    orderSummary: 'Order Summary',
    itemsTotal: 'Items Total',
    extraFees: 'Extra Fees',
    extraFeesTotal: 'Extra Fees Total',
    grandTotal: 'Grand Total',
    notes: 'Notes',
    noItems: 'No items',
    generatedBy: 'Generated by Bakery CMS',
    itemNotePrefix: 'Note',
  },
};

const getBillLanguagePack = (language: InvoiceLanguage): BillLanguagePack => {
  if (language === 'vi' || language === 'en') {
    return BILL_LANGUAGE_PACKS[language];
  }

  return BILL_LANGUAGE_PACKS.en;
};

const DEFAULT_STORE_PROFILE: StoreProfile = {
  name: 'BAKERY CMS',
  logoUrl: null,
};

const normalizeStoreProfile = (
  profile: StoreProfile | null | undefined
): StoreProfile => {
  const name = String(profile?.name ?? '').trim();
  const logoUrl = String(profile?.logoUrl ?? '').trim();

  return {
    name: name || DEFAULT_STORE_PROFILE.name,
    logoUrl: logoUrl.length > 0 ? logoUrl : null,
  };
};

const buildGeneratedByText = (
  language: BillLanguagePack,
  storeName: string
): string => {
  if (language.language === 'vi') {
    return `Tạo bởi ${storeName}`;
  }

  return `Generated by ${storeName}`;
};

const sanitizeFileName = (value: string): string =>
  value.replace(/[^a-zA-Z0-9-_]/g, '_');

const formatBillMoney = (value: number, locale: string): string =>
  `${value.toLocaleString(locale, { minimumFractionDigits: 0, maximumFractionDigits: 2 })} đ`;

const formatBillDateTime = (value: Date, locale: string): string =>
  value.toLocaleString(locale, {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  });

const formatBillProductCode = (item: OrderBillSnapshot['items'][number]): string =>
  item.productCode?.trim() || 'UNKNOWN';

const formatBillProductName = (item: OrderBillSnapshot['items'][number]): string =>
  item.productName?.trim() || 'Unknown Product';

const calculateBillItemsTotal = (snapshot: OrderBillSnapshot): number =>
  snapshot.items.reduce((sum, item) => sum + item.subtotal, 0);

const buildBillSnapshotFromOrder = (order: Order): OrderBillSnapshot => ({
  orderId: order.id,
  orderNumber: order.orderNumber,
  orderType: order.orderType,
  businessModel: order.businessModel,
  totalAmount: order.totalAmount,
  extraAmount: order.extraAmount,
  extraFees: order.extraFees,
  hasPendingExtraPayment: order.hasPendingExtraPayment,
  status: order.status,
  customerName: order.customerName,
  customerPhone: order.customerPhone,
  customerAddress: order.customerAddress,
  notes: order.notes,
  confirmedAt: order.confirmedAt,
  createdAt: order.createdAt,
  items:
    order.items?.map((item) => ({
      productId: item.productId,
      productCode: item.productCode ?? null,
      productName: item.productName ?? null,
      quantity: item.quantity,
      unitPrice: item.unitPrice,
      subtotal: item.subtotal,
      notes: item.notes ?? null,
    })) || [],
});

const base64ToBytes = (base64: string): Uint8Array => {
  const raw = atob(base64);
  const output = new Uint8Array(raw.length);
  for (let index = 0; index < raw.length; index += 1) {
    output[index] = raw.charCodeAt(index);
  }
  return output;
};

const bytesToArrayBuffer = (bytes: Uint8Array): ArrayBuffer => {
  const buffer = new ArrayBuffer(bytes.byteLength);
  new Uint8Array(buffer).set(bytes);
  return buffer;
};

const loadImageWithTimeout = (
  src: string,
  timeoutMs = 3000
): Promise<HTMLImageElement | null> => {
  return new Promise((resolve) => {
    const image = new window.Image();
    image.crossOrigin = 'anonymous';

    const timer = window.setTimeout(() => {
      resolve(null);
    }, timeoutMs);

    image.onload = () => {
      window.clearTimeout(timer);
      resolve(image);
    };

    image.onerror = () => {
      window.clearTimeout(timer);
      resolve(null);
    };

    image.src = src;
  });
};

const createPdfBlobFromJpegDataUrl = (
  jpegDataUrl: string,
  imageWidth: number,
  imageHeight: number
): Blob => {
  const [, base64Content] = jpegDataUrl.split(',');
  if (!base64Content) {
    throw new Error('Invalid image data for PDF export');
  }

  const imageBytes = base64ToBytes(base64Content);
  const encoder = new TextEncoder();
  const encode = (value: string): Uint8Array => encoder.encode(value);

  const objectOffsets: number[] = [0];
  const chunks: Uint8Array[] = [];
  let totalLength = 0;

  const append = (chunk: Uint8Array) => {
    chunks.push(chunk);
    totalLength += chunk.length;
  };

  const appendText = (value: string) => append(encode(value));

  appendText('%PDF-1.4\n%\u00ff\u00ff\u00ff\u00ff\n');

  const startObject = () => {
    objectOffsets.push(totalLength);
  };

  const pageWidth = Math.max(Math.round(imageWidth), 1);
  const pageHeight = Math.max(Math.round(imageHeight), 1);
  const contentStream = `q\n${pageWidth} 0 0 ${pageHeight} 0 0 cm\n/Im0 Do\nQ\n`;
  const contentBytes = encode(contentStream);

  startObject();
  appendText('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n');

  startObject();
  appendText('2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n');

  startObject();
  appendText(
    `3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>\nendobj\n`
  );

  startObject();
  appendText(
    `4 0 obj\n<< /Type /XObject /Subtype /Image /Width ${pageWidth} /Height ${pageHeight} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${imageBytes.length} >>\nstream\n`
  );
  append(imageBytes);
  appendText('\nendstream\nendobj\n');

  startObject();
  appendText(`5 0 obj\n<< /Length ${contentBytes.length} >>\nstream\n`);
  append(contentBytes);
  appendText('endstream\nendobj\n');

  const xrefOffset = totalLength;
  appendText('xref\n0 6\n0000000000 65535 f \n');
  for (let index = 1; index <= 5; index += 1) {
    appendText(`${String(objectOffsets[index]).padStart(10, '0')} 00000 n \n`);
  }
  appendText(`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`);

  return new Blob(chunks.map(bytesToArrayBuffer), { type: 'application/pdf' });
};

const downloadBlob = (blob: Blob, fileName: string): void => {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  link.remove();
  setTimeout(() => {
    URL.revokeObjectURL(url);
  }, 0);
};

const exportBillSnapshotAsPdf = async (
  snapshot: OrderBillSnapshot,
  fileName: string,
  billLanguage: BillLanguagePack,
  storeProfile: StoreProfile
): Promise<void> => {
  const canvas = await renderBillSnapshotToCanvas(
    snapshot,
    billLanguage,
    storeProfile
  );
  const jpegDataUrl = canvas.toDataURL('image/jpeg', 0.92);
  const pdfBlob = createPdfBlobFromJpegDataUrl(
    jpegDataUrl,
    canvas.width,
    canvas.height
  );

  downloadBlob(pdfBlob, `${sanitizeFileName(fileName)}.pdf`);
};

const renderBillSnapshotToCanvas = async (
  snapshot: OrderBillSnapshot,
  billLanguage: BillLanguagePack,
  storeProfile: StoreProfile
): Promise<HTMLCanvasElement> => {
  const locale = billLanguage.locale;
  const normalizedStore = normalizeStoreProfile(storeProfile);
  const storeName = normalizedStore.name;
  const logoImage = normalizedStore.logoUrl
    ? await loadImageWithTimeout(normalizedStore.logoUrl)
    : null;
  const canvas = document.createElement('canvas');
  const width = 1400;
  const rowHeight = 46;
  const margin = 40;
  const headerHeight = 170;
  const infoHeight = 182;
  const tableHeaderHeight = 46;
  const tableRowsHeight = Math.max(snapshot.items.length, 1) * rowHeight;
  const extraFeeRowsCount = snapshot.extraFees.length;
  const totalHeight =
    124 + (extraFeeRowsCount > 0 ? 56 + extraFeeRowsCount * 24 : 0);
  const notesHeight = snapshot.notes ? 96 : 0;
  const footerHeight = 50;
  const height =
    margin * 2 +
    headerHeight +
    18 +
    infoHeight +
    18 +
    tableHeaderHeight +
    tableRowsHeight +
    18 +
    totalHeight +
    (notesHeight ? 16 + notesHeight : 0) +
    16 +
    footerHeight;

  canvas.width = width;
  canvas.height = height;

  const ctx = canvas.getContext('2d');
  if (!ctx) {
    throw new Error('Canvas is not supported');
  }

  const drawRoundedRect = (
    x: number,
    y: number,
    w: number,
    h: number,
    r: number,
    fillStyle: string | CanvasGradient,
    strokeStyle?: string
  ) => {
    ctx.beginPath();
    ctx.moveTo(x + r, y);
    ctx.lineTo(x + w - r, y);
    ctx.quadraticCurveTo(x + w, y, x + w, y + r);
    ctx.lineTo(x + w, y + h - r);
    ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
    ctx.lineTo(x + r, y + h);
    ctx.quadraticCurveTo(x, y + h, x, y + h - r);
    ctx.lineTo(x, y + r);
    ctx.quadraticCurveTo(x, y, x + r, y);
    ctx.closePath();
    ctx.fillStyle = fillStyle;
    ctx.fill();
    if (strokeStyle) {
      ctx.strokeStyle = strokeStyle;
      ctx.stroke();
    }
  };

  const fitText = (value: string, maxWidth: number): string => {
    if (ctx.measureText(value).width <= maxWidth) return value;
    let text = value;
    while (text.length > 3 && ctx.measureText(`${text}...`).width > maxWidth) {
      text = text.slice(0, -1);
    }
    return `${text}...`;
  };

  const createdAt = formatBillDateTime(snapshot.createdAt, locale);

  ctx.fillStyle = '#eef2f7';
  ctx.fillRect(0, 0, width, height);

  const cardX = margin;
  const cardY = margin;
  const cardW = width - margin * 2;
  const cardH = height - margin * 2;
  drawRoundedRect(cardX, cardY, cardW, cardH, 24, '#ffffff', '#dbe2ea');

  const headerX = cardX + 22;
  const headerY = cardY + 22;
  const headerW = cardW - 44;
  drawRoundedRect(headerX, headerY, headerW, headerHeight, 18, '#0f766e');

  const rightGradient = ctx.createLinearGradient(
    headerX + headerW * 0.55,
    headerY,
    headerX + headerW,
    headerY + headerHeight
  );
  rightGradient.addColorStop(0, '#0f766e');
  rightGradient.addColorStop(1, '#14b8a6');
  drawRoundedRect(headerX + headerW * 0.48, headerY, headerW * 0.52, headerHeight, 18, rightGradient);

  const logoSize = logoImage ? 56 : 0;
  const logoGap = logoImage ? 14 : 0;
  const logoX = headerX + 24;
  const logoY = headerY + 20;
  const titleX = headerX + 24 + logoSize + logoGap;

  if (logoImage) {
    drawRoundedRect(logoX, logoY, logoSize, logoSize, 12, '#ffffff');
    ctx.save();
    ctx.beginPath();
    ctx.moveTo(logoX + 12, logoY);
    ctx.lineTo(logoX + logoSize - 12, logoY);
    ctx.quadraticCurveTo(logoX + logoSize, logoY, logoX + logoSize, logoY + 12);
    ctx.lineTo(logoX + logoSize, logoY + logoSize - 12);
    ctx.quadraticCurveTo(
      logoX + logoSize,
      logoY + logoSize,
      logoX + logoSize - 12,
      logoY + logoSize
    );
    ctx.lineTo(logoX + 12, logoY + logoSize);
    ctx.quadraticCurveTo(logoX, logoY + logoSize, logoX, logoY + logoSize - 12);
    ctx.lineTo(logoX, logoY + 12);
    ctx.quadraticCurveTo(logoX, logoY, logoX + 12, logoY);
    ctx.closePath();
    ctx.clip();
    ctx.drawImage(logoImage, logoX, logoY, logoSize, logoSize);
    ctx.restore();
  }

  ctx.fillStyle = '#ffffff';
  ctx.font = '600 18px Arial';
  ctx.fillText(fitText(storeName, 420), titleX, headerY + 38);
  ctx.font = '700 48px Arial';
  ctx.fillText(billLanguage.invoiceTitle, titleX, headerY + 96);
  ctx.font = '700 28px Arial';
  ctx.textAlign = 'right';
  ctx.fillText(`#${snapshot.orderNumber}`, headerX + headerW - 24, headerY + 66);
  ctx.font = '400 18px Arial';
  ctx.fillText(createdAt, headerX + headerW - 24, headerY + 102);
  ctx.textAlign = 'left';

  const infoY = headerY + headerHeight + 18;
  const infoGap = 16;
  const infoW = (headerW - infoGap) / 2;
  const contactCardHeight = 100;
  const addressY = infoY + contactCardHeight + 10;
  const addressHeight = infoHeight - contactCardHeight - 10;
  drawRoundedRect(headerX, infoY, infoW, contactCardHeight, 14, '#f8fafc', '#e2e8f0');
  drawRoundedRect(headerX + infoW + infoGap, infoY, infoW, contactCardHeight, 14, '#f8fafc', '#e2e8f0');
  drawRoundedRect(headerX, addressY, headerW, addressHeight, 14, '#f8fafc', '#e2e8f0');

  ctx.fillStyle = '#64748b';
  ctx.font = '600 13px Arial';
  ctx.fillText(
    billLanguage.customer.toUpperCase(),
    headerX + 18,
    infoY + 28
  );
  ctx.fillText(
    billLanguage.phone.toUpperCase(),
    headerX + infoW + infoGap + 18,
    infoY + 28
  );
  ctx.fillText(
    billLanguage.address.toUpperCase(),
    headerX + 18,
    addressY + 28
  );

  ctx.fillStyle = '#0f172a';
  ctx.font = '700 24px Arial';
  ctx.fillText(
    fitText(snapshot.customerName || billLanguage.walkInCustomer, infoW - 36),
    headerX + 18,
    infoY + 72
  );
  ctx.fillText(
    fitText(snapshot.customerPhone || billLanguage.na, infoW - 36),
    headerX + infoW + infoGap + 18,
    infoY + 72
  );
  ctx.font = '600 18px Arial';
  ctx.fillText(
    fitText(snapshot.customerAddress || billLanguage.na, headerW - 36),
    headerX + 18,
    addressY + 64
  );

  const tableX = headerX;
  const tableY = infoY + infoHeight + 18;
  const colNoW = 56;
  const colCodeW = 220;
  const colNameW = 340;
  const colQtyW = 110;
  const colUnitW = 250;

  drawRoundedRect(tableX, tableY, headerW, tableHeaderHeight, 12, '#f1f5f9', '#e2e8f0');

  ctx.fillStyle = '#334155';
  ctx.font = '700 14px Arial';
  ctx.fillText('#', tableX + 20, tableY + 30);
  ctx.fillText(billLanguage.productCodeShort, tableX + colNoW + 16, tableY + 30);
  ctx.fillText(
    billLanguage.productName,
    tableX + colNoW + colCodeW + 16,
    tableY + 30
  );
  ctx.textAlign = 'center';
  ctx.fillText(
    billLanguage.qty,
    tableX + colNoW + colCodeW + colNameW + colQtyW / 2,
    tableY + 30
  );
  ctx.textAlign = 'right';
  ctx.fillText(
    billLanguage.unitPrice,
    tableX + colNoW + colCodeW + colNameW + colQtyW + colUnitW - 18,
    tableY + 30
  );
  ctx.fillText(billLanguage.subtotal, tableX + headerW - 18, tableY + 30);
  ctx.textAlign = 'left';

  snapshot.items.forEach((item, index) => {
    const rowY = tableY + tableHeaderHeight + index * rowHeight;
    drawRoundedRect(
      tableX,
      rowY,
      headerW,
      rowHeight,
      0,
      index % 2 === 0 ? '#ffffff' : '#fcfdff',
      '#f1f5f9'
    );

    ctx.fillStyle = '#0f172a';
    ctx.font = '400 16px Arial';
    ctx.fillText(String(index + 1), tableX + 20, rowY + 30);
    ctx.fillText(
      fitText(formatBillProductCode(item), colCodeW - 24),
      tableX + colNoW + 16,
      rowY + 30
    );
    ctx.fillText(
      fitText(
        item.notes?.trim()
          ? `${formatBillProductName(item)} | ${billLanguage.itemNotePrefix}: ${item.notes.trim()}`
          : formatBillProductName(item),
        colNameW - 24
      ),
      tableX + colNoW + colCodeW + 16,
      rowY + 30
    );
    ctx.textAlign = 'center';
    ctx.fillText(
      String(item.quantity),
      tableX + colNoW + colCodeW + colNameW + colQtyW / 2,
      rowY + 30
    );
    ctx.textAlign = 'right';
    ctx.fillText(
      formatBillMoney(item.unitPrice, locale),
      tableX + colNoW + colCodeW + colNameW + colQtyW + colUnitW - 18,
      rowY + 30
    );
    ctx.fillText(formatBillMoney(item.subtotal, locale), tableX + headerW - 18, rowY + 30);
    ctx.textAlign = 'left';
  });

  const safeRows = Math.max(snapshot.items.length, 1);
  if (snapshot.items.length === 0) {
    const rowY = tableY + tableHeaderHeight;
    drawRoundedRect(tableX, rowY, headerW, rowHeight, 0, '#ffffff', '#f1f5f9');
    ctx.fillStyle = '#94a3b8';
    ctx.font = 'italic 15px Arial';
    ctx.fillText(billLanguage.noItems, tableX + 16, rowY + 30);
  }

  const totalsY = tableY + tableHeaderHeight + safeRows * rowHeight + 18;
  const itemsTotalAmount = calculateBillItemsTotal(snapshot);
  const totalBoxW = 360;
  const totalBoxH = totalHeight;
  const totalBoxX = tableX + headerW - totalBoxW;
  drawRoundedRect(totalBoxX, totalsY, totalBoxW, totalBoxH, 14, '#ecfeff', '#99f6e4');

  let lineY = totalsY + 30;
  ctx.fillStyle = '#0f766e';
  ctx.font = '600 14px Arial';
  ctx.fillText(billLanguage.itemsTotal, totalBoxX + 20, lineY);
  ctx.textAlign = 'right';
  ctx.fillText(formatBillMoney(itemsTotalAmount, locale), totalBoxX + totalBoxW - 20, lineY);
  ctx.textAlign = 'left';

  lineY += 24;

  if (snapshot.extraFees.length > 0) {
    ctx.fillStyle = '#0f766e';
    ctx.font = '700 13px Arial';
    ctx.fillText(billLanguage.extraFees, totalBoxX + 20, lineY);
    lineY += 22;

    snapshot.extraFees.forEach((fee) => {
      ctx.fillStyle = '#334155';
      ctx.font = '400 13px Arial';
      ctx.fillText(
        fitText(`+ ${fee.name}`, totalBoxW - 190),
        totalBoxX + 20,
        lineY
      );
      ctx.textAlign = 'right';
      ctx.fillText(
        formatBillMoney(fee.amount, locale),
        totalBoxX + totalBoxW - 20,
        lineY
      );
      ctx.textAlign = 'left';
      lineY += 22;
    });

    lineY += 4;
    ctx.fillStyle = '#0f766e';
    ctx.font = '600 14px Arial';
    ctx.fillText(billLanguage.extraFeesTotal, totalBoxX + 20, lineY);
    ctx.textAlign = 'right';
    ctx.fillText(
      formatBillMoney(snapshot.extraAmount, locale),
      totalBoxX + totalBoxW - 20,
      lineY
    );
    ctx.textAlign = 'left';
    lineY += 30;
  } else {
    lineY += 10;
  }

  ctx.fillStyle = '#115e59';
  ctx.font = '700 16px Arial';
  ctx.fillText(billLanguage.grandTotal, totalBoxX + 20, lineY);
  ctx.textAlign = 'right';
  ctx.font = '700 30px Arial';
  ctx.fillText(
    formatBillMoney(snapshot.totalAmount, locale),
    totalBoxX + totalBoxW - 20,
    lineY + 2
  );
  ctx.textAlign = 'left';

  if (snapshot.notes) {
    const notesY = totalsY + totalBoxH + 16;
    drawRoundedRect(tableX, notesY, headerW, notesHeight, 12, '#f8fafc', '#cbd5e1');
    ctx.fillStyle = '#334155';
    ctx.font = '600 15px Arial';
    ctx.fillText(billLanguage.notes, tableX + 14, notesY + 24);

    ctx.fillStyle = '#475569';
    ctx.font = '400 14px Arial';
    const notesText = fitText(snapshot.notes, headerW - 28);
    ctx.fillText(notesText, tableX + 14, notesY + 54);
  }

  ctx.fillStyle = '#94a3b8';
  ctx.font = '400 13px Arial';
  ctx.textAlign = 'center';
  ctx.fillText(buildGeneratedByText(billLanguage, storeName), width / 2, cardY + cardH - 20);
  ctx.textAlign = 'left';

  return canvas;
};

const exportBillSnapshotAsImage = async (
  snapshot: OrderBillSnapshot,
  fileName: string,
  billLanguage: BillLanguagePack,
  storeProfile: StoreProfile
): Promise<void> => {
  const canvas = await renderBillSnapshotToCanvas(
    snapshot,
    billLanguage,
    storeProfile
  );
  const imageDataUrl = canvas.toDataURL('image/png');
  const imageBase64 = imageDataUrl.split(',')[1];

  if (!imageBase64) {
    throw new Error('Invalid image data for invoice export');
  }

  const pngBlob = new Blob([bytesToArrayBuffer(base64ToBytes(imageBase64))], {
    type: 'image/png',
  });
  downloadBlob(pngBlob, `${sanitizeFileName(fileName)}.png`);
};

export const OrderDetailPage: React.FC = () => {
  const { t } = useTranslation();
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { visible, open, close } = useModal();
  const { success, error: showError } = useNotification();

  const [order, setOrder] = useState<Order | null>(null);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [confirmModalVisible, setConfirmModalVisible] = useState(false);
  const [confirmPaymentMethod, setConfirmPaymentMethod] = useState<PaymentMethod>(PaymentMethod.CASH);
  const [confirmingPayment, setConfirmingPayment] = useState(false);
  const [vietQRData, setVietQRData] = useState<VietQRData | null>(null);
  const [vietQRModalVisible, setVietQRModalVisible] = useState(false);
  const [activeTab, setActiveTab] = useState<'overview' | 'bill' | 'payments'>('overview');
  const [orderPayments, setOrderPayments] = useState<Payment[]>([]);
  const [orderPaymentsLoading, setOrderPaymentsLoading] = useState(false);
  const [refundModalVisible, setRefundModalVisible] = useState(false);
  const [refundSubmitting, setRefundSubmitting] = useState(false);
  const [loadingRefundable, setLoadingRefundable] = useState(false);
  const [refundableAmount, setRefundableAmount] = useState(0);
  const [refundForm] = Form.useForm<RefundFormValues>();
  const [manageExtrasModalVisible, setManageExtrasModalVisible] = useState(false);
  const [extrasSubmitting, setExtrasSubmitting] = useState(false);
  const [extrasForm] = Form.useForm<ManageExtrasFormValues>();
  const [extraFeeTemplates, setExtraFeeTemplates] = useState<OrderExtraFeeTemplate[]>([]);
  const [orderBills, setOrderBills] = useState<OrderBill[]>([]);
  const [loadingBills, setLoadingBills] = useState(false);
  const [previewBill, setPreviewBill] = useState<{
    title: string;
    snapshot: OrderBillSnapshot;
    mode: 'draft' | 'saved';
  } | null>(null);
  const [billPreviewVisible, setBillPreviewVisible] = useState(false);
  const [savingBill, setSavingBill] = useState(false);
  const [voidBillModalVisible, setVoidBillModalVisible] = useState(false);
  const [voidReason, setVoidReason] = useState('');
  const [billToVoid, setBillToVoid] = useState<OrderBill | null>(null);
  const [voidingBill, setVoidingBill] = useState(false);
  const [invoiceLanguage, setInvoiceLanguage] = useState<InvoiceLanguage>('en');
  const [storeProfile, setStoreProfile] = useState<StoreProfile>(DEFAULT_STORE_PROFILE);

  const billLanguage = useMemo(
    () => getBillLanguagePack(invoiceLanguage),
    [invoiceLanguage]
  );

  const paymentColumns: ColumnsType<Payment> = useMemo(
    () => [
      {
        title: t('payments.table.paymentId'),
        dataIndex: 'id',
        key: 'id',
        ellipsis: true,
      },
      {
        title: t('payments.table.amount'),
        dataIndex: 'amount',
        key: 'amount',
        width: 140,
        align: 'right',
        render: (amount: number) => formatCurrency(amount),
      },
      {
        title: t('payments.table.paymentType'),
        dataIndex: 'paymentType',
        key: 'paymentType',
        width: 130,
        render: (paymentType: PaymentType) => {
          const labelMap: Record<PaymentType, string> = {
            [PaymentType.PAYMENT]: t('payments.type.payment'),
            [PaymentType.REFUND]: t('payments.type.refund'),
          };

          return (
            <Tag color={paymentType === PaymentType.REFUND ? 'magenta' : 'blue'}>
              {labelMap[paymentType] || paymentType}
            </Tag>
          );
        },
      },
      {
        title: t('payments.table.method'),
        dataIndex: 'method',
        key: 'method',
        width: 140,
        render: (method: PaymentMethod) => {
          const labelMap: Record<PaymentMethod, string> = {
            [PaymentMethod.CASH]: t('payments.method.cash'),
            [PaymentMethod.VIETQR]: t('payments.method.vietqr'),
            [PaymentMethod.BANK_TRANSFER]: t('payments.method.bankTransfer'),
          };
          return labelMap[method] || method;
        },
      },
      {
        title: t('payments.table.status'),
        dataIndex: 'status',
        key: 'status',
        width: 140,
        render: (status: PaymentStatus) => {
          const statusColorMap: Record<PaymentStatus, string> = {
            [PaymentStatus.PENDING]: 'warning',
            [PaymentStatus.PAID]: 'success',
            [PaymentStatus.FAILED]: 'error',
            [PaymentStatus.CANCELLED]: 'default',
          };
          const labelMap: Record<PaymentStatus, string> = {
            [PaymentStatus.PENDING]: t('payments.status.pending'),
            [PaymentStatus.PAID]: t('payments.status.paid'),
            [PaymentStatus.FAILED]: t('payments.status.failed'),
            [PaymentStatus.CANCELLED]: t('payments.status.cancelled'),
          };
          return <Tag color={statusColorMap[status]}>{labelMap[status] || status}</Tag>;
        },
      },
      {
        title: t('payments.table.createdAt'),
        dataIndex: 'createdAt',
        key: 'createdAt',
        width: 180,
        render: (createdAt: Date) => formatDateTime(createdAt),
      },
      {
        title: t('payments.table.actions'),
        key: 'actions',
        width: 120,
        render: (_, record) => (
          <Button
            type="link"
            size="small"
            icon={<EyeOutlined />}
            onClick={() => navigate(`/payments/${record.id}`)}
          >
            {t('payments.actions.view')}
          </Button>
        ),
      },
    ],
    [navigate, t]
  );

  const extraFeeTemplateById = useMemo(
    () => new Map(extraFeeTemplates.map((template) => [template.id, template])),
    [extraFeeTemplates]
  );

  const loadBillSettings = useCallback(async () => {
    try {
      const settingsResult = await settingsService.getSystemSettings();
      if (settingsResult.success) {
        setInvoiceLanguage(settingsResult.data.invoiceLanguage);
        setStoreProfile(normalizeStoreProfile(settingsResult.data.storeProfile));
      }
    } catch {
      // Keep default bill settings when settings cannot be loaded.
    }
  }, []);

  const toMoney = (value: number): number => Math.round(value * 100) / 100;

  const calculateRefundableAmount = (payments: readonly Payment[]): number => {
    const totalPaid = payments
      .filter(
        (payment) =>
          payment.paymentType === PaymentType.PAYMENT &&
          payment.status === PaymentStatus.PAID
      )
      .reduce((sum, payment) => sum + payment.amount, 0);

    const totalRefunded = payments
      .filter(
        (payment) =>
          payment.paymentType === PaymentType.REFUND &&
          payment.status === PaymentStatus.PAID
      )
      .reduce((sum, payment) => sum + payment.amount, 0);

    return Math.max(toMoney(totalPaid - totalRefunded), 0);
  };

  const fetchBills = useCallback(async (orderId: string) => {
    try {
      setLoadingBills(true);
      const result = await getOrderBills(orderId);

      if (result.success) {
        setOrderBills([...(result.data || [])]);
      } else {
        showError(result.error.message);
      }
    } catch (err) {
      const message =
        err instanceof Error
          ? err.message
          : t('orders.bill.notifications.loadFailed', 'Failed to load order bills');
      showError(message);
    } finally {
      setLoadingBills(false);
    }
  }, [showError, t]);

  const fetchPayments = useCallback(async (orderId: string) => {
    try {
      setOrderPaymentsLoading(true);
      const result = await getAllPayments({ orderId });

      if (result.success) {
        setOrderPayments([...(result.data.payments || [])]);
      } else {
        showError(result.error.message);
      }
    } catch (err) {
      const message =
        err instanceof Error
          ? err.message
          : t('payments.notifications.operationFailed', 'Failed to fetch payments');
      showError(message);
    } finally {
      setOrderPaymentsLoading(false);
    }
  }, [showError, t]);

  // Fetch order data
  useEffect(() => {
    const fetchOrder = async () => {
      if (!id) {
        setLoading(false);
        return;
      }

      try {
        setLoading(true);
        const result = await getOrderById(id);

        if (result.success) {
          setOrder(result.data);
          await fetchBills(result.data.id);
        } else {
          showError(result.error.message);
        }
      } catch (err) {
        const message = err instanceof Error ? err.message : t('orders.notifications.operationFailed', 'Failed to fetch order');
        showError(message);
      } finally {
        setLoading(false);
      }
    };

    fetchOrder();
  }, [fetchBills, id, showError, t]);

  useEffect(() => {
    if (activeTab === 'payments' && order && orderPayments.length === 0 && !orderPaymentsLoading) {
      void fetchPayments(order.id);
    }
  }, [activeTab, fetchPayments, order, orderPayments.length, orderPaymentsLoading]);

  useEffect(() => {
    void loadBillSettings();
  }, [loadBillSettings]);

  // Handle edit order
  const handleEdit = () => {
    open();
  };

  // Handle update order
  const handleUpdate = async (values: OrderFormValues) => {
    if (!order) return;

    try {
      setSubmitting(true);

      // Convert form values to update payload
      const updatePayload = {
        orderType: values.orderType,
        businessModel: values.businessModel,
        customerName: values.customerName || undefined,
        customerPhone: values.customerPhone || undefined,
        customerAddress: values.customerAddress || undefined,
        notes: values.notes || undefined,
        items: values.items.map((item) => ({
          productId: item.productId,
          quantity: item.quantity,
          unitPrice: item.unitPrice,
          subtotal: item.quantity * item.unitPrice,
          notes: item.notes || undefined,
        })),
        extraFees: (values.extraFees || []).map((fee) => ({
          id: fee.id,
          name: fee.name,
          amount: fee.amount,
        })),
        status: values.status,
      };

      const result = await updateOrder(order.id, updatePayload);

      if (result.success) {
        setOrder(result.data);
        success(t('orders.notifications.updated', 'Order updated successfully'));
        close();
      } else {
        showError(result.error.message);
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : t('orders.notifications.operationFailed', 'Failed to update order');
      showError(message);
    } finally {
      setSubmitting(false);
    }
  };

  // Handle delete order
  const handleDelete = async () => {
    if (!order) return;

    try {
      const result = await deleteOrder(order.id);

      if (result.success) {
        success(t('orders.notifications.deleted', 'Order deleted successfully'));
        navigate('/orders');
      } else {
        showError(result.error.message);
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : t('orders.notifications.deleteFailed', 'Failed to delete order');
      showError(message);
    }
  };

  const openConfirmModal = () => {
    setConfirmPaymentMethod(PaymentMethod.CASH);
    setConfirmModalVisible(true);
  };

  const closeConfirmModal = () => {
    if (confirmingPayment) {
      return;
    }
    setConfirmModalVisible(false);
  };

  // Handle confirm order
  const handleConfirm = async () => {
    if (!order) return;

    try {
      setConfirmingPayment(true);
      const result = await confirmOrder(order.id, confirmPaymentMethod);

      if (result.success) {
        setOrder(result.data.order);
        setConfirmModalVisible(false);
        success(t('orders.notifications.confirmed', 'Order confirmed successfully'));

        if (result.data.vietqr?.qrDataURL) {
          setVietQRData(result.data.vietqr);
          setVietQRModalVisible(true);
        }
      } else {
        showError(result.error.message);
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : t('orders.notifications.confirmFailed', 'Failed to confirm order');
      showError(message);
    } finally {
      setConfirmingPayment(false);
    }
  };

  // Handle cancel order
  const handleCancel = async () => {
    if (!order) return;

    try {
      const result = await cancelOrder(order.id);

      if (result.success) {
        setOrder(result.data);
        success(t('orders.notifications.cancelled', 'Order cancelled successfully'));
      } else {
        showError(result.error.message);
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : t('orders.notifications.cancelFailed', 'Failed to cancel order');
      showError(message);
    }
  };

  // Handle back navigation
  const handleBack = () => {
    navigate('/orders');
  };

  const handleViewPayments = async () => {
    if (!order) return;

    setActiveTab('payments');
    await fetchPayments(order.id);
  };

  const openManageExtrasModal = async () => {
    if (!order) return;

    const settingsResult = await settingsService.getSystemSettings();
    if (!settingsResult.success) {
      showError(settingsResult.error.message);
      return;
    }

    setInvoiceLanguage(settingsResult.data.invoiceLanguage);
    setStoreProfile(normalizeStoreProfile(settingsResult.data.storeProfile));

    const templates = [...(settingsResult.data.orderExtraFees || [])];
    const mappedOrderFees = (order.extraFees || [])
      .map((fee) => {
        const byId = fee.id ? templates.find((template) => template.id === fee.id) : undefined;
        const byName = !byId
          ? templates.find((template) => template.name === fee.name)
          : undefined;
        const matched = byId || byName;
        if (!matched) {
          return null;
        }

        return {
          id: matched.id,
          name: matched.name,
          amount: fee.amount,
        };
      })
      .filter(
        (fee): fee is { id: string; name: string; amount: number } => fee !== null
      );

    setExtraFeeTemplates(templates);

    extrasForm.setFieldsValue({
      extraFees: mappedOrderFees,
      paymentMethod: PaymentMethod.CASH,
      paymentNotes: '',
    });

    setManageExtrasModalVisible(true);
  };

  const handleManageExtras = async (values: ManageExtrasFormValues) => {
    if (!order) return;

    try {
      setExtrasSubmitting(true);

      const result = await updateOrderExtras(order.id, {
        extraFees: (values.extraFees || [])
          .map((fee) => {
            const template = extraFeeTemplateById.get(fee.id || '');
            if (!template) {
              return null;
            }
            return {
              id: template.id,
              name: template.name,
              amount: Number(fee.amount) || 0,
            };
          })
          .filter(
            (fee): fee is { id: string; name: string; amount: number } =>
              fee !== null
          ),
        paymentMethod: values.paymentMethod,
        paymentNotes: values.paymentNotes?.trim() || undefined,
      });

      if (!result.success) {
        showError(result.error.message);
        return;
      }

      setOrder(result.data.order);
      setManageExtrasModalVisible(false);
      extrasForm.resetFields();
      success(
        t('orders.notifications.extrasUpdated', 'Order extras updated successfully')
      );

      if (result.data.vietqr?.qrDataURL) {
        setVietQRData(result.data.vietqr);
        setVietQRModalVisible(true);
      }

      if (activeTab === 'payments' || result.data.paymentId) {
        await fetchPayments(order.id);
      }
    } catch (err) {
      const message =
        err instanceof Error
          ? err.message
          : t(
              'orders.notifications.extrasUpdateFailed',
              'Failed to update order extras'
            );
      showError(message);
    } finally {
      setExtrasSubmitting(false);
    }
  };

  const handleExtraTemplateSelect = (templateId: string, index: number) => {
    const template = extraFeeTemplateById.get(templateId);
    if (!template) {
      return;
    }

    const currentExtraFees = extrasForm.getFieldValue('extraFees') || [];
    currentExtraFees[index] = {
      ...currentExtraFees[index],
      id: template.id,
      name: template.name,
      amount:
        typeof currentExtraFees[index]?.amount === 'number'
          ? currentExtraFees[index].amount
          : template.defaultAmount,
    };

    extrasForm.setFieldsValue({ extraFees: currentExtraFees });
  };

  const openRefundModal = async () => {
    if (!order) return;

    try {
      setLoadingRefundable(true);
      const result = await getAllPayments({ orderId: order.id });

      if (!result.success) {
        showError(result.error.message);
        return;
      }

      const refundable = calculateRefundableAmount(result.data.payments || []);
      if (refundable <= 0) {
        showError(
          t(
            'orders.refund.noRefundableBalance',
            'No refundable amount remaining for this order.'
          )
        );
        return;
      }

      setRefundableAmount(refundable);
      refundForm.setFieldsValue({
        amount: refundable,
        method: PaymentMethod.BANK_TRANSFER,
        transactionId: '',
        notes: '',
      });
      setRefundModalVisible(true);
    } catch (err) {
      const message =
        err instanceof Error
          ? err.message
          : t(
              'orders.notifications.operationFailed',
              'Failed to calculate refundable amount'
            );
      showError(message);
    } finally {
      setLoadingRefundable(false);
    }
  };

  const handleRefund = async (values: RefundFormValues) => {
    if (!order) return;

    try {
      setRefundSubmitting(true);

      const payload = {
        amount: toMoney(values.amount),
        method: values.method,
        transactionId: values.transactionId?.trim() || undefined,
        notes: values.notes?.trim() || undefined,
      };

      const result = await refundOrderPayment(order.id, payload);

      if (result.success) {
        success(t('orders.notifications.refunded', 'Refund created successfully'));
        setRefundModalVisible(false);
        refundForm.resetFields();

        const refreshedOrder = await getOrderById(order.id);
        if (refreshedOrder.success) {
          setOrder(refreshedOrder.data);
        }

        if (activeTab === 'payments') {
          await fetchPayments(order.id);
        }
      } else {
        showError(result.error.message);
      }
    } catch (err) {
      const message =
        err instanceof Error
          ? err.message
          : t('orders.notifications.refundFailed', 'Failed to create refund');
      showError(message);
    } finally {
      setRefundSubmitting(false);
    }
  };

  const openDraftBillPreview = () => {
    if (!order) return;

    setPreviewBill({
      title: t('orders.bill.previewTitle', 'Bill Preview'),
      snapshot: buildBillSnapshotFromOrder(order),
      mode: 'draft',
    });
    setBillPreviewVisible(true);
  };

  const openSavedBillPreview = (bill: OrderBill) => {
    setPreviewBill({
      title: `${t('orders.bill.savedBill', 'Saved Bill')} ${bill.billNumber}`,
      snapshot: bill.snapshot,
      mode: 'saved',
    });
    setBillPreviewVisible(true);
  };

  const handleSaveBill = async () => {
    if (!order) return;

    try {
      setSavingBill(true);
      const result = await saveOrderBill(order.id);

      if (result.success) {
        success(t('orders.bill.notifications.saved', 'Bill saved successfully'));
        setBillPreviewVisible(false);
        setPreviewBill(null);
        await fetchBills(order.id);
      } else {
        showError(result.error.message);
      }
    } catch (err) {
      const message =
        err instanceof Error
          ? err.message
          : t('orders.bill.notifications.saveFailed', 'Failed to save bill');
      showError(message);
    } finally {
      setSavingBill(false);
    }
  };

  const openVoidBillModal = (bill: OrderBill) => {
    setBillToVoid(bill);
    setVoidReason('');
    setVoidBillModalVisible(true);
  };

  const handleVoidBill = async () => {
    if (!order || !billToVoid) return;

    const reason = voidReason.trim();
    if (reason.length < 3) {
      showError(t('orders.bill.voidReasonMin', 'Please enter a valid reason (at least 3 characters).'));
      return;
    }

    try {
      setVoidingBill(true);
      const result = await voidOrderBill(order.id, billToVoid.id, reason);

      if (result.success) {
        success(t('orders.bill.notifications.voided', 'Bill has been voided'));
        setVoidBillModalVisible(false);
        setBillToVoid(null);
        setVoidReason('');
        await fetchBills(order.id);
      } else {
        showError(result.error.message);
      }
    } catch (err) {
      const message =
        err instanceof Error
          ? err.message
          : t('orders.bill.notifications.voidFailed', 'Failed to void bill');
      showError(message);
    } finally {
      setVoidingBill(false);
    }
  };

  const handleExportBillPdf = async () => {
    if (!previewBill) return;

    try {
      const fileName = `bill_${previewBill.snapshot.orderNumber}_${new Date().toISOString()}`;
      await exportBillSnapshotAsPdf(
        previewBill.snapshot,
        fileName,
        billLanguage,
        storeProfile
      );
    } catch (err) {
      const message =
        err instanceof Error
          ? err.message
          : t('orders.bill.notifications.exportPdfFailed', 'Failed to export PDF');
      showError(message);
    }
  };

  const handleExportBillImage = async () => {
    if (!previewBill) return;

    try {
      const fileName = `bill_${previewBill.snapshot.orderNumber}_${new Date().toISOString()}`;
      await exportBillSnapshotAsImage(
        previewBill.snapshot,
        fileName,
        billLanguage,
        storeProfile
      );
      success(t('orders.bill.notifications.exportedImage', 'Bill image downloaded'));
    } catch (err) {
      const message =
        err instanceof Error
          ? err.message
          : t('orders.bill.notifications.exportImageFailed', 'Failed to export image');
      showError(message);
    }
  };

  // Convert order to form initial values
  const getFormInitialValues = (): OrderFormValues | undefined => {
    if (!order) return undefined;

    return {
      orderType: order.orderType,
      businessModel: order.businessModel,
      customerName: order.customerName || '',
      customerPhone: order.customerPhone || '',
      customerAddress: order.customerAddress || '',
      notes: order.notes || '',
      items:
        order.items?.map((item) => ({
          productId: item.productId,
          quantity: item.quantity,
          unitPrice: item.unitPrice,
          notes: item.notes || '',
        })) || [],
      extraFees:
        order.extraFees?.map((fee) => ({
          id: fee.id,
          name: fee.name,
          amount: fee.amount,
        })) || [],
      status: order.status,
    };
  };

  const activeBill = orderBills.find((bill) => bill.status === 'active') || null;

  const billColumns: ColumnsType<OrderBill> = [
    {
      title: t('orders.bill.billNumber', 'Bill No.'),
      dataIndex: 'billNumber',
      key: 'billNumber',
      width: 180,
      render: (value: string) => <Text strong>{value}</Text>,
    },
    {
      title: t('orders.bill.version', 'Version'),
      dataIndex: 'version',
      key: 'version',
      width: 90,
      align: 'center',
    },
    {
      title: t('orders.bill.status', 'Status'),
      dataIndex: 'status',
      key: 'status',
      width: 120,
      render: (value: OrderBill['status']) => (
        <Tag color={value === 'active' ? 'green' : 'default'}>
          {value === 'active'
            ? t('orders.bill.statusActive', 'Active')
            : t('orders.bill.statusVoided', 'Voided')}
        </Tag>
      ),
    },
    {
      title: t('orders.bill.createdAt', 'Saved At'),
      dataIndex: 'createdAt',
      key: 'createdAt',
      width: 180,
      render: (value: Date) => formatDateTime(value),
    },
    {
      title: t('orders.bill.voidReason', 'Void Reason'),
      dataIndex: 'voidReason',
      key: 'voidReason',
      render: (value: string | null) => value || <Text type="secondary">-</Text>,
    },
    {
      title: t('orders.bill.actions', 'Actions'),
      key: 'actions',
      width: 200,
      render: (_, record) => (
        <Space size="small">
          <Button
            type="link"
            size="small"
            icon={<EyeOutlined />}
            onClick={() => openSavedBillPreview(record)}
          >
            {t('orders.actions.view')}
          </Button>
          {record.status === 'active' && (
            <Button
              type="link"
              size="small"
              danger
              icon={<DeleteOutlined />}
              onClick={() => openVoidBillModal(record)}
            >
              {t('orders.bill.voidBill', 'Void Bill')}
            </Button>
          )}
        </Space>
      ),
    },
  ];

  // Loading state
  if (loading) {
    return <LoadingSpinner fullScreen />;
  }

  // Order not found
  if (!order) {
    return <EmptyState description={t('orders.list.noOrders', "The order you're looking for doesn't exist.")} />;
  }

  return (
    <>
      <Tabs
        activeKey={activeTab}
        onChange={(key) => setActiveTab(key as 'overview' | 'bill' | 'payments')}
        items={[
          {
            key: 'overview',
            label: t('orders.tabs.overview', 'Overview'),
            children: (
              <OrderDetail
                order={order}
                onEdit={handleEdit}
                onDelete={handleDelete}
                onConfirm={openConfirmModal}
                onCancel={handleCancel}
                onViewPayments={handleViewPayments}
                onRefund={openRefundModal}
                onManageExtras={openManageExtrasModal}
                onBack={handleBack}
              />
            ),
          },
          {
            key: 'bill',
            label: t('orders.tabs.bill', 'Bill'),
            children: (
              <Card
                title={t('orders.bill.sectionTitle', 'Order Bill')}
                extra={
                  <Space wrap>
                    <Button icon={<EyeOutlined />} onClick={openDraftBillPreview}>
                      {t('orders.bill.showDraft', 'Show Bill')}
                    </Button>
                  </Space>
                }
              >
                <Space direction="vertical" size={12} style={{ width: '100%' }}>
                  {activeBill ? (
                    <Text type="secondary">
                      {t('orders.bill.activeBillHint', 'Active bill')}: {activeBill.billNumber}
                    </Text>
                  ) : (
                    <Text type="secondary">
                      {t(
                        'orders.bill.noActiveBillHint',
                        'No active bill. Save a bill to lock this version before printing.'
                      )}
                    </Text>
                  )}

                  <Table<OrderBill>
                    rowKey="id"
                    loading={loadingBills}
                    dataSource={orderBills}
                    columns={billColumns}
                    pagination={false}
                    locale={{
                      emptyText: t('orders.bill.noBills', 'No saved bill yet'),
                    }}
                    scroll={{ x: 900 }}
                  />
                </Space>
              </Card>
            ),
          },
          {
            key: 'payments',
            label: t('orders.tabs.payments', 'Payments'),
            children: (
              <Card
                title={`${t('orders.actions.viewPayments')} #${order.orderNumber}`}
                extra={
                  <Space wrap>
                    <Button
                      icon={<ReloadOutlined />}
                      onClick={() => void fetchPayments(order.id)}
                      loading={orderPaymentsLoading}
                    >
                      {t('common.actions.refresh', 'Refresh')}
                    </Button>
                    {order.status === 'paid' && (
                      <Button onClick={openRefundModal}>
                        {t('orders.actions.refundOrder')}
                      </Button>
                    )}
                  </Space>
                }
              >
                {order.hasPendingExtraPayment && (
                  <div style={{ marginBottom: 12 }}>
                    <Tag color="red">
                      {t(
                        'orders.detail.pendingExtraPayment',
                        'Extra payment is pending for this order'
                      )}
                    </Tag>
                  </div>
                )}
                {orderPaymentsLoading ? (
                  <div style={{ display: 'flex', justifyContent: 'center', padding: '24px 0' }}>
                    <Spin />
                  </div>
                ) : orderPayments.length === 0 ? (
                  <EmptyState description={t('payments.list.noPayments')} />
                ) : (
                  <Space direction="vertical" style={{ width: '100%' }} size={12}>
                    <Text type="secondary">
                      {t('payments.table.totalPayments', { total: orderPayments.length })}
                    </Text>
                    <Table<Payment>
                      rowKey="id"
                      columns={paymentColumns}
                      dataSource={orderPayments}
                      pagination={false}
                      scroll={{ x: 860 }}
                    />
                  </Space>
                )}
              </Card>
            ),
          },
        ]}
      />

      <Modal
        title={t('orders.extras.modalTitle', 'Manage Extra Fees')}
        open={manageExtrasModalVisible}
        onCancel={() => {
          if (extrasSubmitting) return;
          setManageExtrasModalVisible(false);
          extrasForm.resetFields();
        }}
        onOk={() => extrasForm.submit()}
        okText={t('common.actions.save', 'Save')}
        cancelText={t('common.actions.cancel', 'Cancel')}
        confirmLoading={extrasSubmitting}
      >
        <Space direction="vertical" style={{ width: '100%' }} size={12}>
          <Text type="secondary">
            {order.status === 'paid'
              ? t(
                  'orders.extras.paidDescription',
                  'If total extra fees increase, a new payment will be created to collect the additional amount.'
                )
              : order.status === 'confirmed'
                ? t(
                    'orders.extras.confirmedDescription',
                    'If total extra fees increase, the pending payment will be regenerated with updated amount.'
                  )
                : t(
                    'orders.extras.defaultDescription',
                    'Extra fees are added to this order total.'
                  )}
          </Text>
          <Form<ManageExtrasFormValues>
            form={extrasForm}
            layout="vertical"
            onFinish={handleManageExtras}
          >
            <Form.List name="extraFees">
              {(fields, { add, remove }) => (
                <Space direction="vertical" size={8} style={{ width: '100%' }}>
                  {fields.map((field, index) => (
                    <Space key={field.key} style={{ display: 'flex' }} align="baseline">
                      <Form.Item
                        {...field}
                        name={[field.name, 'id']}
                        rules={[
                          {
                            required: true,
                            message: t(
                              'orders.form.validation.extraFeeNameRequired',
                              'Required'
                            ),
                          },
                        ]}
                        style={{ marginBottom: 0, flex: 1 }}
                      >
                        <Select
                          placeholder={t('orders.form.extraFeeNamePlaceholder', 'Fee name')}
                          options={extraFeeTemplates.map((template) => ({
                            value: template.id,
                            label: template.name,
                          }))}
                          disabled={extraFeeTemplates.length === 0}
                          onChange={(value) => handleExtraTemplateSelect(value, index)}
                        />
                      </Form.Item>
                      <Form.Item
                        {...field}
                        name={[field.name, 'name']}
                        style={{ display: 'none' }}
                      >
                        <Input />
                      </Form.Item>
                      <Form.Item
                        {...field}
                        name={[field.name, 'amount']}
                        rules={[
                          {
                            required: true,
                            message: t(
                              'orders.form.validation.extraFeeAmountRequired',
                              'Required'
                            ),
                          },
                          {
                            type: 'number',
                            min: 0,
                            message: t(
                              'orders.form.validation.extraFeeAmountMin',
                              'Must be at least 0'
                            ),
                          },
                        ]}
                        style={{ marginBottom: 0, width: 160 }}
                      >
                        <InputNumber
                          min={0}
                          style={{ width: '100%' }}
                          placeholder={t('orders.form.extraFeeAmountPlaceholder', 'Amount')}
                        />
                      </Form.Item>
                      <Button
                        type="text"
                        danger
                        icon={<DeleteOutlined />}
                        onClick={() => remove(field.name)}
                      />
                    </Space>
                  ))}
                  <Button
                    type="dashed"
                    icon={<PlusOutlined />}
                    onClick={() => {
                      if (extraFeeTemplates.length === 0) {
                        return;
                      }

                      const currentExtraFees = extrasForm.getFieldValue('extraFees') || [];
                      const usedIds = new Set(
                        currentExtraFees
                          .map((fee: { id?: string }) => fee.id)
                          .filter(Boolean)
                      );
                      const templateToAdd =
                        extraFeeTemplates.find((template) => !usedIds.has(template.id)) ||
                        extraFeeTemplates[0];

                      add({
                        id: templateToAdd?.id || '',
                        name: templateToAdd?.name || '',
                        amount: templateToAdd?.defaultAmount || 0,
                      });
                    }}
                    disabled={extraFeeTemplates.length === 0}
                    block
                  >
                    {t('orders.form.addExtraFee', 'Add Extra Fee')}
                  </Button>
                  {extraFeeTemplates.length === 0 && (
                    <Text type="secondary">
                      {t(
                        'orders.form.noExtraFeeTemplates',
                        'No extra fee templates configured in settings.'
                      )}
                    </Text>
                  )}
                </Space>
              )}
            </Form.List>

            {(order.status === 'paid' || order.status === 'confirmed') && (
              <>
                <Form.Item
                  label={t('orders.confirm.paymentMethodLabel')}
                  name="paymentMethod"
                >
                  <Select<PaymentMethod>
                    options={[
                      { value: PaymentMethod.CASH, label: t('payments.method.cash') },
                      { value: PaymentMethod.BANK_TRANSFER, label: t('payments.method.bankTransfer') },
                      { value: PaymentMethod.VIETQR, label: t('payments.method.vietqr') },
                    ]}
                  />
                </Form.Item>
                <Form.Item
                  label={t('payments.form.notes')}
                  name="paymentNotes"
                >
                  <Input.TextArea
                    rows={2}
                    maxLength={500}
                    placeholder={t('payments.form.notesPlaceholder')}
                  />
                </Form.Item>
              </>
            )}
          </Form>
        </Space>
      </Modal>

      <Modal
        title={t('orders.confirm.selectPaymentMethodTitle')}
        open={confirmModalVisible}
        onCancel={closeConfirmModal}
        onOk={handleConfirm}
        okText={t('orders.actions.confirmOrder')}
        cancelText={t('orders.confirm.no')}
        confirmLoading={confirmingPayment}
      >
        <div style={{ display: 'grid', gap: 12 }}>
          <Text>{t('orders.confirm.paymentMethodDescription')}</Text>
          <div>
            <Text strong>{t('payments.detail.paymentType')}</Text>
          </div>
          <Select<PaymentType>
            value={PaymentType.PAYMENT}
            disabled
            options={[{ value: PaymentType.PAYMENT, label: t('payments.type.payment') }]}
            style={{ width: '100%' }}
          />
          <div>
            <Text strong>{t('orders.confirm.paymentMethodLabel')}</Text>
          </div>
          <Select<PaymentMethod>
            value={confirmPaymentMethod}
            onChange={setConfirmPaymentMethod}
            options={[
              { value: PaymentMethod.CASH, label: t('payments.method.cash') },
              { value: PaymentMethod.BANK_TRANSFER, label: t('payments.method.bankTransfer') },
              { value: PaymentMethod.VIETQR, label: t('payments.method.vietqr') },
            ]}
            style={{ width: '100%' }}
          />
        </div>
      </Modal>

      <Modal
        title={t('orders.confirm.vietqrTitle')}
        open={vietQRModalVisible}
        onCancel={() => {
          setVietQRModalVisible(false);
          setVietQRData(null);
        }}
        footer={null}
      >
        <div style={{ display: 'grid', gap: 12, textAlign: 'center' }}>
          <Text>{t('orders.confirm.vietqrDescription')}</Text>
          {vietQRData?.qrDataURL && (
            <div style={{ display: 'flex', justifyContent: 'center' }}>
              <Image src={vietQRData.qrDataURL} width={280} preview={false} />
            </div>
          )}
          {vietQRData && (
            <div style={{ display: 'grid', gap: 4 }}>
              <Text>{vietQRData.accountName}</Text>
              <Text>{vietQRData.accountNo}</Text>
              <Text>{vietQRData.addInfo}</Text>
            </div>
          )}
        </div>
      </Modal>

      <Modal
        title={t('orders.refund.modalTitle', 'Create Refund')}
        open={refundModalVisible}
        onCancel={() => {
          if (refundSubmitting) return;
          setRefundModalVisible(false);
          refundForm.resetFields();
        }}
        onOk={() => refundForm.submit()}
        okText={t('orders.refund.submit', 'Refund')}
        cancelText={t('orders.confirm.no')}
        confirmLoading={refundSubmitting || loadingRefundable}
      >
        <Space direction="vertical" style={{ width: '100%' }} size={12}>
          <Text type="secondary">
            {t('orders.refund.availableAmount', 'Refundable amount')}: {formatCurrency(refundableAmount)}
          </Text>
          <Form<RefundFormValues>
            form={refundForm}
            layout="vertical"
            onFinish={handleRefund}
          >
            <Form.Item
              label={t('payments.form.amount')}
              name="amount"
              rules={[
                { required: true, message: t('payments.form.amountRequired') },
                { type: 'number', min: 0.01, message: t('payments.form.amountPositive') },
                {
                  validator: async (_, value?: number) => {
                    if (!value) return Promise.resolve();
                    if (value > refundableAmount) {
                      return Promise.reject(
                        new Error(
                          t(
                            'orders.refund.exceedsRefundable',
                            'Refund amount exceeds refundable balance'
                          )
                        )
                      );
                    }
                    return Promise.resolve();
                  },
                },
              ]}
            >
              <InputNumber
                style={{ width: '100%' }}
                min={0}
                max={refundableAmount}
                precision={2}
                placeholder={t('payments.form.amountPlaceholder')}
              />
            </Form.Item>

            <Form.Item
              label={t('payments.form.method')}
              name="method"
              rules={[{ required: true, message: t('payments.form.methodRequired') }]}
            >
              <Select<PaymentMethod>
                options={[
                  { value: PaymentMethod.CASH, label: t('payments.method.cash') },
                  { value: PaymentMethod.BANK_TRANSFER, label: t('payments.method.bankTransfer') },
                  { value: PaymentMethod.VIETQR, label: t('payments.method.vietqr') },
                ]}
                placeholder={t('payments.form.methodPlaceholder')}
              />
            </Form.Item>

            <Form.Item label={t('payments.form.transactionId')} name="transactionId">
              <Input placeholder={t('payments.form.transactionIdPlaceholder')} />
            </Form.Item>

            <Form.Item label={t('payments.form.notes')} name="notes">
              <Input.TextArea
                rows={3}
                maxLength={500}
                showCount
                placeholder={t('payments.form.notesPlaceholder')}
              />
            </Form.Item>
          </Form>
        </Space>
      </Modal>

      <Modal
        title={t('orders.bill.voidTitle', 'Void bill')}
        open={voidBillModalVisible}
        onCancel={() => {
          if (voidingBill) return;
          setVoidBillModalVisible(false);
          setBillToVoid(null);
          setVoidReason('');
        }}
        onOk={handleVoidBill}
        confirmLoading={voidingBill}
        okText={t('orders.bill.confirmVoid', 'Confirm void')}
        cancelText={t('orders.confirm.no')}
      >
        <Space direction="vertical" size={10} style={{ width: '100%' }}>
          <Text>
            {t(
              'orders.bill.voidDescription',
              'Bill will be marked as voided and kept for history. Enter reason to continue.'
            )}
          </Text>
          {billToVoid && (
            <Text strong>
              {t('orders.bill.billNumber', 'Bill No.')}: {billToVoid.billNumber}
            </Text>
          )}
          <Input.TextArea
            rows={4}
            value={voidReason}
            onChange={(event) => setVoidReason(event.target.value)}
            maxLength={1000}
            showCount
            placeholder={t('orders.bill.voidReasonPlaceholder', 'Enter reason for voiding this bill')}
          />
        </Space>
      </Modal>

      <Modal
        title={previewBill?.title || t('orders.bill.previewTitle', 'Bill Preview')}
        open={billPreviewVisible}
        onCancel={() => {
          setBillPreviewVisible(false);
          setPreviewBill(null);
        }}
        footer={[
          previewBill?.mode === 'draft' ? (
            <Button
              key="save"
              type="primary"
              loading={savingBill}
              disabled={Boolean(activeBill)}
              onClick={() => void handleSaveBill()}
            >
              {t('orders.bill.saveBill', 'Save Bill')}
            </Button>
          ) : null,
          <Button
            key="image"
            icon={<FileImageOutlined />}
            onClick={() => {
              void handleExportBillImage();
            }}
          >
            {t('orders.bill.exportImage', 'Export Image')}
          </Button>,
          <Button
            key="pdf"
            icon={<FilePdfOutlined />}
            onClick={() => {
              void handleExportBillPdf();
            }}
          >
            {t('orders.bill.exportPdf', 'Export PDF')}
          </Button>,
        ]}
        width={980}
      >
        {previewBill && (
          <div
            style={{
              background: '#f5f7fb',
              borderRadius: 14,
              padding: 14,
            }}
          >
            <Card
              style={{
                marginBottom: 14,
                borderRadius: 12,
                borderColor: '#e2e8f0',
              }}
              bodyStyle={{ padding: 0 }}
            >
              <div
                style={{
                  padding: 16,
                  background: 'linear-gradient(135deg, #0f766e, #14b8a6)',
                  color: '#ffffff',
                  borderRadius: '12px 12px 0 0',
                  display: 'flex',
                  justifyContent: 'space-between',
                  gap: 12,
                  flexWrap: 'wrap',
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                  {storeProfile.logoUrl && (
                    <Image
                      src={storeProfile.logoUrl}
                      width={52}
                      height={52}
                      preview={false}
                      style={{
                        borderRadius: 10,
                        objectFit: 'cover',
                        border: '1px solid rgba(255,255,255,0.5)',
                        background: '#ffffff',
                      }}
                    />
                  )}
                  <div>
                    <Text style={{ color: '#ccfbf1', fontSize: 12 }}>
                      {storeProfile.name}
                    </Text>
                    <div
                      style={{
                        color: '#ffffff',
                        fontSize: 28,
                        fontWeight: 700,
                        lineHeight: 1.15,
                      }}
                    >
                      {billLanguage.invoiceTitle}
                    </div>
                  </div>
                </div>
                <div style={{ textAlign: 'right' }}>
                  <div style={{ color: '#ffffff', fontSize: 20, fontWeight: 700 }}>
                    #{previewBill.snapshot.orderNumber}
                  </div>
                  <Text style={{ color: '#e6fffb' }}>
                    {formatBillDateTime(previewBill.snapshot.createdAt, billLanguage.locale)}
                  </Text>
                </div>
              </div>

              <div style={{ padding: 14 }}>
                <div
                  style={{
                    display: 'grid',
                    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
                    gap: 10,
                  }}
                >
                  <div
                    style={{
                      border: '1px solid #e2e8f0',
                      background: '#fafafa',
                      borderRadius: 10,
                      padding: '10px 12px',
                    }}
                  >
                    <Text type="secondary" style={{ fontSize: 12 }}>
                      {billLanguage.customer}
                    </Text>
                    <div style={{ fontWeight: 600 }}>
                      {previewBill.snapshot.customerName || billLanguage.walkInCustomer}
                    </div>
                  </div>
                  <div
                    style={{
                      border: '1px solid #e2e8f0',
                      background: '#fafafa',
                      borderRadius: 10,
                      padding: '10px 12px',
                    }}
                  >
                    <Text type="secondary" style={{ fontSize: 12 }}>
                      {billLanguage.phone}
                    </Text>
                    <div style={{ fontWeight: 600 }}>
                      {previewBill.snapshot.customerPhone || billLanguage.na}
                    </div>
                  </div>
                  <div
                    style={{
                      border: '1px solid #e2e8f0',
                      background: '#fafafa',
                      borderRadius: 10,
                      padding: '10px 12px',
                      gridColumn: '1 / -1',
                    }}
                  >
                    <Text type="secondary" style={{ fontSize: 12 }}>
                      {billLanguage.address}
                    </Text>
                    <div style={{ fontWeight: 600 }}>
                      {previewBill.snapshot.customerAddress || billLanguage.na}
                    </div>
                  </div>
                </div>
              </div>
            </Card>

            <Card
              size="small"
              style={{ borderRadius: 12, borderColor: '#e2e8f0' }}
              bodyStyle={{ padding: 12 }}
            >
              <Space
                style={{ width: '100%', justifyContent: 'space-between', marginBottom: 10 }}
                wrap
              >
                <Text type="secondary">
                  {billLanguage.items} ({previewBill.snapshot.items.length})
                </Text>
                <Text strong style={{ fontSize: 18, color: '#0f766e' }}>
                  {formatCurrency(
                    previewBill.snapshot.totalAmount,
                    'VND',
                    billLanguage.locale
                  )}
                </Text>
              </Space>

              <Table<OrderBillSnapshot['items'][number]>
                rowKey={(item) =>
                  `${item.productId}-${item.productCode || 'UNKNOWN'}-${item.quantity}-${item.unitPrice}`
                }
                dataSource={[...previewBill.snapshot.items]}
                bordered
                size="middle"
                pagination={false}
                scroll={{ x: 1120 }}
                columns={[
                  {
                    title: '#',
                    key: 'index',
                    width: 60,
                    align: 'center',
                    render: (_value, _item, index) => index + 1,
                  },
                  {
                    title: billLanguage.productCode,
                    dataIndex: 'productCode',
                    key: 'productCode',
                    width: 170,
                    render: (value: string | null) => <Text code>{value || 'UNKNOWN'}</Text>,
                  },
                  {
                    title: billLanguage.productName,
                    dataIndex: 'productName',
                    key: 'productName',
                    render: (value: string | null) => (
                      <Text strong>{value || billLanguage.na}</Text>
                    ),
                  },
                  {
                    title: billLanguage.qty,
                    dataIndex: 'quantity',
                    key: 'quantity',
                    width: 90,
                    align: 'center',
                  },
                  {
                    title: billLanguage.unitPrice,
                    dataIndex: 'unitPrice',
                    key: 'unitPrice',
                    width: 140,
                    align: 'right',
                    render: (value: number) =>
                      formatCurrency(value, 'VND', billLanguage.locale),
                  },
                  {
                    title: billLanguage.subtotal,
                    dataIndex: 'subtotal',
                    key: 'subtotal',
                    width: 140,
                    align: 'right',
                    render: (value: number) => (
                      <Text strong>
                        {formatCurrency(value, 'VND', billLanguage.locale)}
                      </Text>
                    ),
                  },
                  {
                    title: billLanguage.notes,
                    dataIndex: 'notes',
                    key: 'notes',
                    width: 210,
                    render: (value: string | null) =>
                      value?.trim() ? value : <Text type="secondary">{billLanguage.na}</Text>,
                  },
                ]}
                summary={() => {
                  const itemTotal = calculateBillItemsTotal(previewBill.snapshot);
                  return (
                    <>
                      <Table.Summary.Row>
                        <Table.Summary.Cell index={0} colSpan={6} align="right">
                          <Text strong>{billLanguage.itemsTotal}:</Text>
                        </Table.Summary.Cell>
                        <Table.Summary.Cell index={1} align="right">
                          <Text strong>
                            {formatCurrency(itemTotal, 'VND', billLanguage.locale)}
                          </Text>
                        </Table.Summary.Cell>
                      </Table.Summary.Row>
                      {previewBill.snapshot.extraFees.map((fee) => (
                        <Table.Summary.Row key={fee.id}>
                          <Table.Summary.Cell index={0} colSpan={6} align="right">
                            <Text>{`+ ${fee.name}`}</Text>
                          </Table.Summary.Cell>
                          <Table.Summary.Cell index={1} align="right">
                            <Text>
                              {formatCurrency(fee.amount, 'VND', billLanguage.locale)}
                            </Text>
                          </Table.Summary.Cell>
                        </Table.Summary.Row>
                      ))}
                      <Table.Summary.Row>
                        <Table.Summary.Cell index={0} colSpan={6} align="right">
                          <Text strong>{billLanguage.extraFeesTotal}:</Text>
                        </Table.Summary.Cell>
                        <Table.Summary.Cell index={1} align="right">
                          <Text strong>
                            {formatCurrency(
                              previewBill.snapshot.extraAmount,
                              'VND',
                              billLanguage.locale
                            )}
                          </Text>
                        </Table.Summary.Cell>
                      </Table.Summary.Row>
                      <Table.Summary.Row>
                        <Table.Summary.Cell index={0} colSpan={6} align="right">
                          <Text strong>{billLanguage.grandTotal}:</Text>
                        </Table.Summary.Cell>
                        <Table.Summary.Cell index={1} align="right">
                          <Text strong style={{ fontSize: 16, color: '#115e59' }}>
                            {formatCurrency(
                              previewBill.snapshot.totalAmount,
                              'VND',
                              billLanguage.locale
                            )}
                          </Text>
                        </Table.Summary.Cell>
                      </Table.Summary.Row>
                    </>
                  );
                }}
              />
            </Card>

            {previewBill.snapshot.notes && (
              <Card
                size="small"
                style={{ marginTop: 12, borderRadius: 12, borderColor: '#cbd5e1', background: '#f8fafc' }}
                bodyStyle={{ padding: 12 }}
              >
                <Text strong>{billLanguage.notes}:</Text>
                <div style={{ marginTop: 6 }}>
                  <Text>{previewBill.snapshot.notes}</Text>
                </div>
              </Card>
            )}
          </div>
        )}
      </Modal>

      <OrderForm
        open={visible}
        onClose={close}
        onSubmit={handleUpdate}
        initialValues={getFormInitialValues()}
        loading={submitting}
      />
    </>
  );
};
